version: '3.9'
services:
  # container 1 - golang image with entrypoint to run tests
  app:
    image: golang:latest
    working_dir: /app/task
    entrypoint: ["go", "test", "--tags=integration" ,"./...", "-v", "-p=1"]
    volumes:
      - $PWD/..:/app
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8201
      - PROJECT_ID=dummy-project-id
    depends_on:
      - firestore_emulator

  # container 2 - firestore emulator
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8201
    restart: on-failure